### PR TITLE
Updated debian/ directory with small fixes

### PR DESCRIPTION
**Pull request by rafael2k**
Updated debian/ directory with small fixes and information about improvements.

### CODE REVIEW

**Comment by morrownr** [comment]
Merged.

Rafael, I consider you the owner of the debian folder. When I have time, I will try to catch up on what you are doing. If you see anything I need to do with the code, scripts or docs to support your effort, let me know.

Nick

**Comment by rafael2k** [comment]
First of all, thanks for your work Nick! The debian packaging system in a way overlap in functionality with your installation scripts, as it will create a package which uses the dkms infrastructure in debian-based systems. But for now, I think it is fine to keep both, at the option to the user to use the bash install scripts, or the debian way of packaging.

**Comment by rafael2k** [comment]
Btw, I added the package (rtl8821cu-dkms) with the latest sources here:
http://packages.hermes.radio/

**Comment by morrownr** [comment]
Rafael,

Okay, I understand what you are doing. Glad you are doing it. This has been requested by users before but I have a certain amount of time to work this project. I have 3 additional Realtek drivers here as well as a LOT of information about adapters with in-kernel drivers. You are welcome to add a short blurb in the installation section of the README that points them to an entry in the FAQ that explains things... if you want.

Nick

**Comment by rafael2k** [comment]
Hi Nick,
I'll do a PR adding some basic instructions on how to use the debian dir.

**Pull request merged**
