### PR TITLE
makefile: cleanup whitespace

### PR DESCRIPTION
**Pull request by paralin**
Cleanup some whitespace errors in Makefile.

### CODE REVIEW

**Comment by morrownr** [comment]
@paralin 

I have delayed merging this PR because I need to clean up some stuff first. I will merge it though.

Are you interested in working on and testing the new version of this driver that we are working on right now? I could certainly use some whitespace testing as well as testing on other systems.

Nick

**Comment by paralin** [comment]
Hey @morrownr you've added me to the repo for the new one already and I'll definitely test it out. How private do you want to keep your fork - I can make a branch of SkiffOS with the new version & send to some users I know are using the driver, but I don't know if you want it shared yet or not.

**Comment by morrownr** [comment]
Hi @paralin 

> How private do you want to keep your fork - I can make a branch of SkiffOS with the new version & send to some users I know are using the driver, but I don't know if you want it shared yet or not.

I would prefer that you not send the new driver to others at this point. If you know individuals that would like to test, forward their github names to me and I will add them to the repo so they can test.

I am going to be doing additional work as far as the installation and removal scripts are concerned. I also need good reviews of README and 8821cu.conf as they contain the documentation. You might want to consider working with someone else that runs SkiffOS so as to integrate information about it in the README like is already done with several distros. The information from all of this effort, once proven to be good, will be merged into the other 4 Realtek repos so that effort could shine a light on SkiffOS as this site averages over 10,000 hits per week. No kidding!

Quiet frankly, the driver itself appears to be in good shape. We may find a couple of things here and there but my goal is to reduce problem reports by >50% and that will primarily be accomplished by working on the scripts and the docs.

Nick

Nick

**Comment by paralin** [comment]
Ok - do you mean you want me to add it to the SkiffOS readme or the other way around? Not sure exactly what you'd like me to do.

We use your current driver in the buildroot / skiff tree:

 - https://github.com/skiffos/SkiffOS/blob/40643804463801271f63c90a76127ef3c25797b6/configs/odroid/common/buildroot/wifi#L3
 - https://github.com/skiffos/buildroot/blob/skiff/package/rtl8821cu/rtl8821cu.mk

And it's submitted to the buildroot upstream as well:

http://patchwork.ozlabs.org/project/buildroot/patch/20221201014538.679048-1-christian@paral.in/

**Comment by morrownr** [comment]
> Ok - do you mean you want me to add it to the SkiffOS readme or the other way around?

Well, too many pronouns I guess. Let me see what I can do:

The driver README.md, which is the main page you see when you go to my driver repo, (new or old but I would prefer you to look at the new one) contains several sections that refer to various distros. There are also specific instructions in other sections that are specific to specific distros. This ends up being good advertising. I am offering you the opportunity to go through the README.md and add SkiffOS information if you see any value in it. This site, github.com/morrownr, averages over 10,000 hits per week so when I say it ends up being good advertising, I mean it.

I understand that SkiffOS evidently has its own method of installing this driver but I do not understand it. You are welcome to enlighten me. Generally speaking, I am not sure that doing such is a good idea unless you have someone that stays right on top of any changes because I have to make changes regularly for the driver to continue to work on new kernels. Case in point: Arch and Manjaro users end up here filing bugs that are not a problem with what I do here but rather the maintainer is this driver in their AUR, as they call it, is not keeping things current. That kinda annoys me because it is causing me work I should not have to do. I end telling them they can use the driver here, which is up to date, or they can use the one in AUR and complain to whomever maintains it. This is just another example where the lack of a basic standardization in areas where it is needed is very toxic to the acceptance of Linux in many environments. I'm not focusing the aggravation at you, I'm just throwing out some of my thoughts based on my experience of using Linux since 1994.

Nick

**Comment by paralin** [comment]
> generally speaking, I am not sure that doing such is a good idea unless you have someone that stays right on top of any changes because I have to make changes regularly for the driver to continue to work on new kernels

We have a number of these packages in buildroot including rtl8821au, about 10 of them. All are nearly identical and just build the kernel module using buildroots compilation infrastructure.

I linked the package above (the mk file).

There's no other way to build and install kernel modules in the context of buildroot, and using the package works fine. We do regularly update the package with the latest commit, but all packages are version pinned and hashed so we do have to select a specific commit or release in the package file.

Generally we keep the package updated with the latest version and will respond to users reporting build errors by bumping the package to the latest as well.

I think generally we are faster about keeping buildroot up to date with the latest versions of packages than for example, Ubuntu or arch, which tend to be quite slow.

Hopefully that helps clarify a bit!

**Comment by paralin** [comment]
@morrownr to respond to the point about the readme: I'd definitely appreciate a link to skiffos and buildroot (buildroot.org) in there! I can also add a docs page to link to which explains how to enable the driver there.

The above linked mailing list entry is me attempting to upstream the package to buildroot proper, at the moment the patch is pending merge.

**Comment by paralin** [comment]
@morrownr rtl8821cu is now enabled on all SkiffOS configurations on default. No user action required

**Comment by morrownr** [comment]
Done. Thanks.

**Pull request merged**
